[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "pysequoia"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 4 - Beta",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
authors = [
  {name = "Wiktor Kwapisiewicz", email = "wiktor@metacode.biz"}
]
keywords = ["openpgp", "pgp", "gpg", "gnupg", "sequoia"]
license = {file = "LICENSE"}
description = "Provides OpenPGP facilities using Sequoia-PGP library"

[project.urls]
"Homepage" = "https://codeberg.org/wiktor/pysequoia"
"Bug Tracker" = "https://codeberg.org/wiktor/pysequoia/issues"
